version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/finantial_system
      - node_modules:/app/node_modules
    ports:
      - "3000:3000"

volumes:
  db_data:
  node_modules:
