version: '3'

services:
  database:
    image: postgres:12
    volumes:
      - db_data:/var/lib/postgresql/data
  app:
    build:
      context: .
      dockerfile: Dockerfile
    command: bash -c "rm -f tmp/pids/server.pid && rails db:create db:migrate"
    depends_on:
      - database
    volumes:
      - .:/finantial_system
      - node_modules:/app/node_modules
    ports:
      - "3000:3000"

volumes:
  db_data:
  node_modules:
