version: '3.3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/finantial_system
      - .:/app
      - node_modules:/app/node_modules
    ports:
      - "3000:3000"

volumes:
  db_data:
  node_modules:
