version: '3.3'

services:
  db:
    image: postgres:12
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
  app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
    volumes:
      - .:/finantial_system
      - .:/app
      - node_modules:/app/node_modules
    ports:
      - "3000:3000"

volumes:
  db_data:
  node_modules:
