databases:
  - name: finances_system
    databaseName: finances_system
    user: postgres

services:
  - type: web
    name: finances_system
    env: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: finances_system
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false