default: &default
  adapter: postgresql
  encoding: unicode
  username: postgres
  password: postgres
  host: <%= ENV['DATABASE_URL'] || 'db' %>
  port: <%= ENV['DATABASE_PORT'] || '5432' %>
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: finantial_system_development

test:
  <<: *default
  database: finantial_system_test

production:
  <<: *default
  database: finantial_system_production
