default: &default
  adapter: postgresql
  encoding: unicode
  username: postgres
  password: postgres
  host: db
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: finantial_system_development

test:
  <<: *default
  database: finantial_system_test

production:
  <<: *default
  database: finantial_system_production
